# What is TensorFlow?

![](https://upload.wikimedia.org/wikipedia/commons/a/a4/TensorFlowLogo.png)


TensorFlow is an open source software library released in 2015 by Google to make it easier for developers to design, build, and train deep learning models. TensorFlow originated as an internal library that Google developers used to build models in-house, and we expect additional functionality to be added to the open source version as they are tested and vetted in the internal flavor. Although TensorFlow is only one of several options available to developers, we choose to use it here because of its thoughtful design and ease of use. We’ll briefly compare TensorFlow to alternatives in the next section.

At a high level, TensorFlow is a Python library that allows users to express arbitrary computation as a graph of data flows. Nodes in this graph represent mathematical operations, whereas edges represent data that is communicated from one node to another. Data in TensorFlow are represented as tensors, which are multidimensional arrays. Although this framework for thinking about computation is valuable in many different fields, TensorFlow is primarily used for deep learning in practice and research.


## Install
As usual, we'll be using Conda to install TensorFlow. You might already have a TensorFlow environment, but check to make sure you have all the necessary packages.

### OS X or Linux
Run the following commands to setup your environment:

    conda create -n tensorflow python=3.5
    source activate tensorflow
    conda install pandas matplotlib jupyter notebook scipy scikit-learn
    pip install tensorflow

### Windows
And installing on Windows. In your console or Anaconda shell,

    conda create -n tensorflow python=3.5
    activate tensorflow
    conda install pandas matplotlib jupyter notebook scipy scikit-learn
    pip install tensorflow

### Hello, world!
Try running the following code in your Python console to make sure you have TensorFlow properly installed. The console will print "Hello, world!" if TensorFlow is installed. Don’t worry about understanding what it does. You’ll learn about it in the next section.

In [1]:
import tensorflow as tf

In [4]:
hello_constant=tf.constant('Hello World')
hello_constant

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [7]:
# Version Check
import tensorflow as tf
#create tensorflow object called tensor
print("Tensorflow version:{}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

Tensorflow version:2.7.0
Keras version: 2.7.0


### GPU/CPU Check

In [8]:
variable=tf.Variable([3,3])
if tf.test.is_gpu_available():
    print('GPU')
else:
    print('CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
CPU


### Tensor Constant

In [11]:
tensor=tf.constant(42)
tensor
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [10]:
tensor.numpy()

42

In [12]:
tensor.dtype

tf.int32

In [13]:
tensor1=tf.constant(1, dtype=tf.int64)
tensor1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [15]:
tensor_x=tf.constant([[4,2],[9,5]])
print(tensor_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [16]:
tensor_x.numpy()

array([[4, 2],
       [9, 5]])

In [17]:
print(f"shape:\n{tensor_x.shape}")

shape:
(2, 2)


In [18]:
print("Data-Type:",tensor_x.dtype)

Data-Type: <dtype: 'int32'>


### Commonly used method is to generate constant tf.ones and tf.zeros like of numpy np.ones and np.zeros