# What is TensorFlow?

![](https://upload.wikimedia.org/wikipedia/commons/a/a4/TensorFlowLogo.png)


TensorFlow is an open source software library released in 2015 by Google to make it easier for developers to design, build, and train deep learning models. TensorFlow originated as an internal library that Google developers used to build models in-house, and we expect additional functionality to be added to the open source version as they are tested and vetted in the internal flavor. Although TensorFlow is only one of several options available to developers, we choose to use it here because of its thoughtful design and ease of use. We’ll briefly compare TensorFlow to alternatives in the next section.

At a high level, TensorFlow is a Python library that allows users to express arbitrary computation as a graph of data flows. Nodes in this graph represent mathematical operations, whereas edges represent data that is communicated from one node to another. Data in TensorFlow are represented as tensors, which are multidimensional arrays. Although this framework for thinking about computation is valuable in many different fields, TensorFlow is primarily used for deep learning in practice and research.


## Install
As usual, we'll be using Conda to install TensorFlow. You might already have a TensorFlow environment, but check to make sure you have all the necessary packages.

### OS X or Linux
Run the following commands to setup your environment:

    conda create -n tensorflow python=3.5
    source activate tensorflow
    conda install pandas matplotlib jupyter notebook scipy scikit-learn
    pip install tensorflow

### Windows
And installing on Windows. In your console or Anaconda shell,

    conda create -n tensorflow python=3.5
    activate tensorflow
    conda install pandas matplotlib jupyter notebook scipy scikit-learn
    pip install tensorflow

### Hello, world!
Try running the following code in your Python console to make sure you have TensorFlow properly installed. The console will print "Hello, world!" if TensorFlow is installed. Don’t worry about understanding what it does. You’ll learn about it in the next section.

In [1]:
import tensorflow as tf

In [4]:
hello_constant=tf.constant('Hello World')
hello_constant

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [7]:
# Version Check
import tensorflow as tf
#create tensorflow object called tensor
print("Tensorflow version:{}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

Tensorflow version:2.7.0
Keras version: 2.7.0


### GPU/CPU Check

In [8]:
variable=tf.Variable([3,3])
if tf.test.is_gpu_available():
    print('GPU')
else:
    print('CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
CPU


### Tensor Constant

In [11]:
tensor=tf.constant(42)
tensor
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [10]:
tensor.numpy()

42

In [12]:
tensor.dtype

tf.int32

In [13]:
tensor1=tf.constant(1, dtype=tf.int64)
tensor1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [15]:
tensor_x=tf.constant([[4,2],[9,5]])
print(tensor_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [16]:
tensor_x.numpy()

array([[4, 2],
       [9, 5]])

In [17]:
print(f"shape:\n{tensor_x.shape}")

shape:
(2, 2)


In [18]:
print("Data-Type:",tensor_x.dtype)

Data-Type: <dtype: 'int32'>


### Commonly used method is to generate constant tf.ones and tf.zeros like of numpy np.ones and np.zeros

In [19]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [20]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [21]:
const1=tf.constant([[3,4,5],[2,4,5]]);
const2=tf.constant([[1,2,3],[4,5,6]]);
result=tf.add(const1,const2)
print(result)

tf.Tensor(
[[ 4  6  8]
 [ 6  9 11]], shape=(2, 3), dtype=int32)


### Random Constant

In [28]:
tf.random.normal(shape=(2,2), mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.9712412 , -1.2009478 ],
       [ 0.8507134 ,  0.00264949]], dtype=float32)>

In [26]:
tf.random.uniform(shape=(2,2), minval=0,maxval=10, dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 4],
       [4, 2]])>

### Variable


A variable is a special tensor that is used to store variable values and need to be initialized with some values

### Declaring a variable

In [29]:
var=12#python variable
var1=tf.Variable(42)
var2=tf.Variable([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.],[9.,10.,11.]])# ranl 3 sensor
var, var1,var2

(12,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=float32)>)

### Data type can be explicitely specified

In [30]:
float_64=tf.Variable(89, dtype=tf.float64)
float_64

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=89.0>

### to reassign a variable, use var.assign()

In [35]:
tensor_2=tf.constant(1)
#tensor_2.assign(2)

In [32]:
var_reassign=tf.Variable(89.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [33]:
var_reassign.assign(54)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=54.0>

In [38]:
new_value=tf.random.normal(shape=(2,2))
a=tf.Variable(new_value)
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i,j]==new_value[i,j]
new_value

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.0911499,  1.2925048],
       [-0.9404922,  2.1465063]], dtype=float32)>

In [40]:
added_value=tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j]==new_value[i,j]+added_value[i,j]

In [41]:
added_value

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.5196845 ,  1.1475024 ],
       [-0.48373485,  0.20953108]], dtype=float32)>

### Shaping a tensor

In [59]:
tensor=tf.Variable([[[10.,11.,12.],[13.,14.,15.]],[[16.,17.,18.],[19.,20.,21.]]])
print(tensor.shape)
tensor_01=tf.Variable([[[10.,11.,12.],[13.,14.,15.],[16.,17.,18.],[19.,20.,21.]]])
print(tensor_01.shape)

(2, 2, 3)
(1, 4, 3)


In [56]:
tensor1=tf.reshape(tensor,[2,6])
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [57]:
tensor2=tf.reshape(tensor,[1,12])
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.]],
      dtype=float32)>

### Rank of Tensor

The rank of tensor is defiend as the number of dimensions, which is the number of indices that are required to specify any particular element of that tensor

In [62]:
tf.rank(tensor)
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

### Specifying an element of a tensor

In [58]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

In [65]:
tensor3=tensor[1,0,2]
tensor3


<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

In [66]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

In [67]:
tensor[0][1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([13., 14., 15.], dtype=float32)>

In [68]:
tensor[1][1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([19., 20., 21.], dtype=float32)>

In [69]:
tensor[1][1][1]

<tf.Tensor: shape=(), dtype=float32, numpy=20.0>

### Casting a tensor to a Numpy Variable

In [70]:
print(tensor.numpy())

[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]]


In [75]:
import numpy
print(tensor[1,0,2].numpy())

18.0


### Finding the size or length of a tensor

In [76]:
tensor_size=tf.size(input=tensor).numpy()
tensor_size

12

In [77]:
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

In [78]:
tensor3.dtype

tf.float32

### Tensorflow Mathmatical Operation

In [80]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))
c=a+b
d=tf.square(c)
e=tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 0.34579328 -0.46292663]
 [-0.12398    -1.0976231 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.7245681  -0.06326357]
 [-0.52673    -0.28832227]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 2.0703614  -0.52619016]
 [-0.65071    -1.3859453 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4.286396  0.2768761]
 [0.4234235 1.9208444]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[7.9276876 0.5908517]
 [0.5216753 0.2500873]], shape=(2, 2), dtype=float32)


### Perform element wise operation

In [81]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

In [82]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[100., 121., 144.],
        [169., 196., 225.]],

       [[256., 289., 324.],
        [361., 400., 441.]]], dtype=float32)>

## Broadcasting operation

Element-wise tensor operations support broadcasting in the same way that Numpy arrays do



The simplest example is multiplication of a tensor by a scalar value

In [83]:
tensor4=tensor*4
tensor4

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[40., 44., 48.],
        [52., 56., 60.]],

       [[64., 68., 72.],
        [76., 80., 84.]]], dtype=float32)>

### Transpose Matrix Multiplication

In [87]:
matricx_u=tf.constant([[6,7,6]])
matrix_v=tf.constant([[3,4,3]])
tf.matmul(matricx_u,tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[64]])>

In [89]:
matricx_u1=tf.constant([[6,7,6],[5,6,7]])
matrix_v1=tf.constant([[3,4,3],[7,8,9]])
tf.matmul(matricx_u1, tf.transpose(a=matrix_v1))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 64, 152],
       [ 60, 146]])>

In [90]:
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

###  creating a tensor to another datatype

In [91]:
i=tf.cast(tensor1, dtype=tf.int32)
i

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])>

### Casting with truncation

In [92]:
j=tf.cast(tf.constant(4.9), dtype=tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

### Ragged Tensor

A ragged tensor is a tensor haing one or more ragged dimensions. Ragged dimensions are dimensions that have slices having various lengths. There are variety of methods for the declaration of ragged arrays, the simplest way is declaring a constant ragged array.




### Below example shows how to delcare a constant ragged array

In [93]:
ragged=tf.ragged.constant([[9,7,4,3],[],[11,12,8],[3],[7,8]])
print(ragged)

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>


In [94]:
print(ragged[0,:])

tf.Tensor([9 7 4 3], shape=(4,), dtype=int32)


In [95]:
print(ragged[1,:])

tf.Tensor([], shape=(0,), dtype=int32)


In [96]:
print(ragged[2,:])

tf.Tensor([11 12  8], shape=(3,), dtype=int32)


In [97]:
print(ragged[3,:])

tf.Tensor([3], shape=(1,), dtype=int32)


In [99]:
print(ragged[4,:])

tf.Tensor([7 8], shape=(2,), dtype=int32)


### Squared difference of tensor

In [100]:
varx=[4,5,6,1,2]
vary=8
varz=tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36])>

### Calculate the Mean

function available  tf.reduce_mean()

In [ ]:
#defining a constant
numbers=tf.constant([[8.,9.]])